services:

  nginx:
    image: nginx:stable-alpine
    container_name: global_nginx
    restart: unless-stopped

    ports:
      - 80:80
      - 443:443

    volumes:
      - kango_public:/var/www/kango_express
      - D:/vps_simulator/apps/kango_express/public/uploads:/var/www/kango_express/public/uploads:ro
      - D:/vps_simulator/apps/kango_express/storage:/var/www/kango_express/storage:ro
      # - D:/vps_simulator/apps/kango_express/.env:/var/www/kango_express/.env:ro
      - laravel_app_two_public:/var/www/laravel_app_two:ro
      - ./log/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/etc/nginx/html

    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    
      
volumes:
  kango_public:
    external: true

  laravel_app_two_public:
    external: true
