server {
    listen 80;
    server_name test.kango-post.com;

    location / {
        # Bắn sang container Nginx của dự án A (Cổng 80 mặc định của container đó)
        proxy_pass http://kango-nginx;
    }
}