services:

  kango-app:
    # image: ${IMAGE_NAME}
    image: dongtv1408/kango_express:v1.4.6_a8d651e8
    container_name: kango-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "9000"
    volumes:      
      - ./:/var/www/kango_express
      - ./.env:/var/www/kango_express/.env
      - ./storage:/var/www/kango_express/storage
      - ./public/uploads:/var/www/kango_express/public/uploads
    networks:
      - proxy-network

  kango-nginx:
    image: nginx:stable-alpine
    container_name: kango-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/kango_express
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true